package models;

public enum EstadoPedido {
    PEDIDO_VALIDO,
    PEDIDO_SIN_PRODUCTOS,
    PRODUCTO_CON_CANTIDAD_INSUFICIENTE,
    PEDIDO_CON_DESCUENTO,
    PEDIDO_SIN_DESCUENTO,
    PEDIDO_MARCADO_COMO_FRAUDE,
}
